steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuild-repo/cloudbuild-image:latest', '.']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuild-repo/cloudbuild-image:latest'

options:
  logging: LEGACY

logsBucket: 'gs://my-cloudbuild-logs-docker'
